[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = 'context_filetype.vim'
on_i = 1
hook_source = '''
    call deoplete#enable()
    " No display of the number of competion list
    set shortmess+=c

    " <TAB>: completion.
    inoremap <silent><expr> <TAB>
          \ pumvisible() ? "\<C-n>" :
          \ <SID>check_back_space() ? "\<TAB>" :
          \ deoplete#manual_complete()
    function! s:check_back_space() abort
      let col = col('.') - 1
      return !col || getline('.')[col - 1]  =~ '\s'
    endfunction

    " <S-TAB>: completion back.
    inoremap <expr><S-TAB>  pumvisible() ? "\<C-p>" : "\<C-h>"
    " <C-e>: popup cancel
    inoremap <expr><C-e>       deoplete#cancel_popup()

    call deoplete#custom#source('_', 'matchers', ['matcher_had'])
    call deoplete#custom#source('_', 'converters', [
          \ 'converter_remove_paren',
          \ 'converter_remove_overlap',
          \ 'matcher_length',
          \ 'converter_truncate_abbr',
          \ 'converter_truncate_menu',
          \ 'converter_auto_delimiter',
          \ ])
    call deoplete#custom#option('keyword_patterns', {
          \ '_': '[a-zA-Z_]\k*\(?',
          \ 'tex': '[^\w|\s][a-zA-Z_]\w*',
          \ })
    call deoplete#custom#option('camel_case', v:true)
    set completeopt-=preview
    autocmd InsertLeave,CompleteDone * if pumvisible() == 0 | pclose | endif
'''

[[plugins]]
repo='preservim/nerdtree'
on_i = 1

[[plugins]]
repo='w0ng/vim-hybrid'
on_i=1

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']
hook_add = '''   
    set laststatus=2
    let g:airline_theme='deus'
    let g:airline_powerline_fonts=1
    let g:airline#extensions#tabline#enabled=1
    let g:airline#extensions#tabline#buffer_idx_mode=1
    let g:airline#extensions#virtualenv#enabled=1
    
    " unicode symbols
    "let g:airline_left_sep = 'Â»'
    "let g:airline_left_sep = 'â–¶'
    "let g:airline_right_sep = 'Â«'
    "let g:airline_right_sep = 'â—€'
    "let g:airline_symbols.crypt = 'ğŸ”’'
    "let g:airline_symbols.linenr = 'âŠ'
    "let g:airline_symbols.linenr = 'â¤'
    "let g:airline_symbols.linenr = 'Â¶'
    "let g:airline_symbols.maxlinenr = 'â˜°'
    "let g:airline_symbols.maxlinenr = ''
    "let g:airline_symbols.branch = 'â‡'
    "let g:airline_symbols.paste = 'Ï'
    "let g:airline_symbols.paste = 'Ã'
    "let g:airline_symbols.paste = 'âˆ¥'
    "let g:airline_symbols.spell = 'ê¨'
    "let g:airline_symbols.notexists = 'âˆ„'
    "let g:airline_symbols.whitespace = 'Î'

    " powerline symbols
    let g:airline_left_sep = 'î‚°'
    let g:airline_left_alt_sep = 'î‚±'
    let g:airline_right_sep = 'î‚²'
    let g:airline_right_alt_sep = 'î‚³'
    "let g:airline_symbols.branch = 'î‚ '
    "let g:airline_symbols.readonly = 'î‚¢'
    "let g:airline_symbols.linenr = 'î‚¡'

    " old vim-powerline symbols
    "let g:airline_left_sep = 'â®€'
    "let g:airline_left_alt_sep = 'â®'
    "let g:airline_right_sep = 'â®‚  '
    "let g:airline_right_alt_sep = 'â®ƒ  '
    "let g:airline_symbols.branch = 'â­   '
    "let g:airline_symbols.readonly = 'â­¤  '
    "let g:airline_symbols.linenr = 'â­¡  '
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
